services:
  - type: web
    name: urban-nucleus-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MYSQL_HOST
        fromService:
          type: pserv
          name: urban-nucleus-db
          property: host
      - key: MYSQL_PORT
        fromService:
          type: pserv
          name: urban-nucleus-db
          property: port
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        fromService:
          type: pserv
          name: urban-nucleus-db
          property: password
      - key: MYSQL_DATABASE
        value: urban_nucleus

  - type: pserv
    name: urban-nucleus-db
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
